version: '2'

services:
    web:
        image: lavoweb/php-7.1
        ports:
            - "80:80"
        volumes:
            - ./app:/var/www/html
            - ./docker/config/vhosts:/etc/apache2/sites-enabled
        links:
            - db:db
    db:
        image: mysql:5.5
        volumes:
            - ~/mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
    myadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        links:
            - db:db